# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jakewendt-simply_commentable}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George 'Jake' Wendt"]
  s.date = %q{2011-02-14}
  s.description = %q{longer description of your gem}
  s.email = %q{github@jakewendt.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/models/comment.rb",
    "config/routes.rb",
    "generators/simply_commentable/USAGE",
    "generators/simply_commentable/simply_commentable_generator.rb",
    "generators/simply_commentable/templates/autotest_simply_commentable.rb",
    "generators/simply_commentable/templates/migrations/create_comments.rb",
    "generators/simply_commentable/templates/simply_commentable.rake",
    "lib/jakewendt-simply_commentable.rb",
    "lib/simply_commentable.rb",
    "lib/simply_commentable/assertions.rb",
    "lib/simply_commentable/base.rb",
    "lib/simply_commentable/tasks.rb",
    "lib/simply_commentable/test_tasks.rb",
    "lib/tasks/simply_commentable_tasks.rake"
  ]
  s.homepage = %q{http://github.com/jakewendt/simply_commentable}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{one-line summary of your gem}
  s.test_files = [
    "test/app/controllers/application_controller.rb",
    "test/app/models/post.rb",
    "test/app/models/user.rb",
    "test/factories.rb",
    "test/unit/commentable/comment_test.rb",
    "test/unit/post_test.rb",
    "test/unit/user_test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 2"])
      s.add_runtime_dependency(%q<rails_extension>, [">= 0"])
    else
      s.add_dependency(%q<rails>, ["~> 2"])
      s.add_dependency(%q<rails_extension>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 2"])
    s.add_dependency(%q<rails_extension>, [">= 0"])
  end
end

